services:
  app:
    build: ./Core
    ports:
      - "8080:8080"
    env_file: ./Core/.env
    volumes:
      - /var/log:/app/logs
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - aitu_mom_network

  email-service:
    build:
      context: ./Email
      dockerfile: Dockerfile
    container_name: email-service
    env_file: ./Email/.env
    volumes:
      - /var/log:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - aitu_mom_network

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    env_file: ./Email/.env
    ports:
      # - "15672:15672"  # UI
      - "5672:5672"    # AMQP
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aitu_mom_network 

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./Core/.env
    ports:
      - "5432:5432"
    restart: always
    networks:
      - aitu_mom_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aitu -d aitu_moment"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  aitu_mom_network:

