version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./logs:/var/log
    depends_on:
      - db
    restart: always
    networks:
      - aitu_mom_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "5432:5432"
    restart: always
    networks:
      - aitu_mom_network

volumes:
  postgres_data:

networks:
  aitu_mom_network:

