# Build stage
FROM golang:1.24.3 AS builder

WORKDIR /app/core_service/
# Base directory is AITUmoment

# Copy dependency files first for better caching
COPY core_service/go.mod core_service/go.sum ./

COPY /common ../common

RUN go mod download

# Copy the rest of the application
COPY /core_service/. .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/main.go

# Final stage
FROM alpine:latest

# Add ca-certificates for HTTPS and timezone data
RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/core_service/main .

# Copy necessary application files
COPY ./core_service/pkg/sqlx/migrations/ db/migrations/

# Create directory for logs
RUN mkdir -p /app/logs

ENTRYPOINT ["./main"]
