{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "api gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request duration <300ms over 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum(rate(http_request_duration_ms_bucket{le=\"300\"}[5m])) by (path)\r\n/\r\n  sum(rate(http_request_duration_ms_count[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu seconds rate 30s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"api_gateway\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate of requests 5s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_requests_counter[5s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}