# Build stage
FROM golang:1.24.3 AS builder

WORKDIR /app/email_service/
# Base directory is AITUmoment

# Copy dependency files first for better caching
COPY email_service/go.mod email_service/go.sum ./

COPY /common ../common

RUN go mod download

# Copy the rest of the application
COPY /email_service/. .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/main.go

# Final stage
FROM alpine:latest

# Add ca-certificates for HTTPS and timezone data
RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/email_service/main .

# Create directory for logs
RUN mkdir -p /app/logs

ENTRYPOINT ["./main"]
