name: Go CI

on:
  push:
    branches:
      - microservices-core-service-email-service-with-message-queue 
  pull_request:
    branches:
      - microservices-core-service-email-service-with-message-queue 

env:
  DOCKER_REGISTRY: docker.io # Docker Hub registry URL
  CORE_SERVICE_DOCKER_IMAGE_NAME: a5bbbbb/aitu-moment/core_service 
  API_GATEWAY_DOCKER_IMAGE_NAME: a5bbbbb/aitu-moment/api_gateway 
  EMAIL_SERVICE_DOCKER_IMAGE_NAME: a5bbbbb/aitu-moment/email_service 

jobs:
  build-and-test:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' 

    - name: Tidy Go modules
      run:  cd core_service; go mod tidy 

    - name: Run tests
      run:  cd core_service; APP_MODE=DEV; go test ./internal/test 
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push core_service Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./core_service/dockerfile
        push: true # Set to true to push the image
        tags: |
          ${{ env.CORE_SERVICE_DOCKER_IMAGE_NAME }}:latest
          ${{ env.CORE_SERVICE_DOCKER_IMAGE_NAME }}:${{ github.sha }}
          
    - name: Build and push api_gateway Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./api_gateway/dockerfile
        push: true # Set to true to push the image
        tags: |
          ${{ env.API_GATEWAY_DOCKER_IMAGE_NAME }}:latest
          ${{ env.API_GATEWAY_DOCKER_IMAGE_NAME }}:${{ github.sha }}
          
    - name: Build and push email_service Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./email_service/dockerfile
        push: true # Set to true to push the image
        tags: |
          ${{ env.EMAIL_SERVICE_DOCKER_IMAGE_NAME }}:latest
          ${{ env.EMAIL_SERVICE_DOCKER_IMAGE_NAME }}:${{ github.sha }}